binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- emulator/emu-32-bit.c
- emulator/emu.c
- emulator/profemu.c
- flite/Setup.hs
- flite/fl-parsec.hs
- flite/fl-pure.hs
- flite/fl.hs
- fpga/Main.hs
- ghc-flite/src/GhcFlite/Translate.hs
- hf/H2F.hs
- hf/Translate.old.hs
- hf/hf.hs
- york-lava/examples/Poly/Poly.hs
- york-lava/examples/Toggle/Toggle.hs
