binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- emulator/emu-32-bit.c
- emulator/emu.c
- emulator/profemu.c
- flite/Setup.hs
- flite/examples/Adjoxo.hs
- flite/examples/Braun.hs
- flite/examples/Cichelli.hs
- flite/examples/Clausify.hs
- flite/examples/Countdown.hs
- flite/examples/Fib.hs
- flite/examples/KnuthBendix.hs
- flite/examples/MSS.hs
- flite/examples/Mate.hs
- flite/examples/OrdList.hs
- flite/examples/Parts.hs
- flite/examples/PermSort.hs
- flite/examples/Queens.hs
- flite/examples/Queens2.hs
- flite/examples/Sudoku.hs
- flite/examples/Taut.hs
- flite/examples/While.hs
- flite/fl-parsec.hs
- flite/fl-pure.hs
- flite/fl.hs
- fpga/Main.hs
- ghc-flite/src/GhcFlite/Translate.hs
- hf/H2F.hs
- hf/Translate.old.hs
- hf/hf.hs
- programs/Echo.hs
- programs/While.hs
- york-lava/examples/Poly/Poly.hs
- york-lava/examples/Toggle/Toggle.hs
